name: Android CI (APK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    # 1) Use Gradle Build Action to run "gradle wrapper" even if wrapper is missing
    - name: Generate Gradle Wrapper (8.7)
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: '8.7'
        arguments: wrapper

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # 2) Install Android SDK pieces (cmdline-tools + platforms + build-tools)
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: |
          cmdline-tools;latest
          platform-tools
          platforms;android-34
          build-tools;34.0.0

    # 3) Create debug keystore so APK is properly signed (v1+v2)
    - name: Generate debug keystore
      run: |
        mkdir -p $HOME/.android
        keytool -genkeypair -v \
          -keystore $HOME/.android/debug.keystore \
          -storepass android -keypass android \
          -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
          -dname "CN=Android Debug,O=Android,C=US"

    # 4) Build the APK with the newly-created wrapper
    - name: Build Debug APK
      run: ./gradlew :app:assembleDebug --no-daemon --stacktrace

    # 5) Upload the APK
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: AutoTapper-debug-apk
        path: app/build/outputs/apk/debug/*.apk
