name: Android CI (APK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Install Gradle & generate wrapper
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install gradle 8.7
        gradle wrapper --gradle-version 8.7

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Generate debug keystore
      run: |
        mkdir -p $HOME/.android
        keytool -genkeypair -v \
          -keystore $HOME/.android/debug.keystore \
          -storepass android -keypass android \
          -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
          -dname "CN=Android Debug,O=Android,C=US"

    - name: Build Debug APK
      run: ./gradlew :app:assembleDebug --no-daemon --stacktrace

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: AutoTapper-debug-apk
        path: app/build/outputs/apk/debug/*.apk
